#!/usr/bin/env python3
"""wch_pioc_gen.py - PIOC 程序 .BIN -> C 接口(.c/.h) 生成器

替代 WCH 官方 BIN_HEX.EXE: 从 WASM53B 汇编出的指令码 .BIN 生成
带 get_code/get_size 接口的规范化 C 源, 供 MCU 侧加载 PIOC 程序:

    #include "<name>.h"
    memcpy((uint8_t *)PIOC_SRAM_BASE, <name>_get_code(), <name>_get_size());
    PIOC->D8_SYS_CFG = RB_MST_CLK_GATE | RB_MST_IO_EN0 | RB_MST_IO_EN1;

用法:
    python wch_pioc_gen.py --bin <in.BIN> --c <out.c> --h <out.h> --name <prefix>

输出接口 (prefix = --name 参数, 如 pioc_iic):
    const unsigned char *<prefix>_get_code(void);   // PIOC 指令码数组指针
    unsigned int        <prefix>_get_size(void);    // 程序字节数
"""
import argparse
import re
import sys

_BYTES_PER_LINE = 16


def _check_name(name: str) -> None:
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        sys.exit(f"wch_pioc_gen.py: invalid --name '{name}' (must be a C identifier)")


def _read_bin(path: str) -> bytes:
    try:
        with open(path, "rb") as f:
            data = f.read()
    except OSError as exc:
        sys.exit(f"wch_pioc_gen.py: cannot read {path}: {exc}")
    if not data:
        sys.exit(f"wch_pioc_gen.py: {path} is empty (assembly produced no code?)")
    return data


def _format_array(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), _BYTES_PER_LINE):
        chunk = data[i : i + _BYTES_PER_LINE]
        lines.append("    " + ",".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)


def _gen_h(name: str) -> str:
    guard = f"WCH_PIOC_{name.upper()}_H"
    return (
        "/* Generated by wch_pioc_gen.py - do not edit */\n"
        f"#ifndef {guard}\n"
        f"#define {guard}\n"
        "\n"
        "#ifdef __cplusplus\n"
        'extern "C" {\n'
        "#endif\n"
        "\n"
        f"/* PIOC 程序接口: 指令码数组与字节数, 用于加载到 PIOC_SRAM_BASE */\n"
        f"const unsigned char *{name}_get_code(void);\n"
        f"unsigned int        {name}_get_size(void);\n"
        "\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif\n"
        "\n"
        f"#endif /* {guard} */\n"
    )


def _gen_c(name: str, data: bytes, bin_path: str) -> str:
    return (
        "/* Generated by wch_pioc_gen.py - do not edit */\n"
        f"/* source: {bin_path} ({len(data)} bytes) */\n"
        f'#include "{name}.h"\n'
        "\n"
        f"static const unsigned char {name}_code[] = {{\n"
        f"{_format_array(data)}\n"
        "};\n"
        "\n"
        f"const unsigned char *{name}_get_code(void)\n"
        "{\n"
        f"    return {name}_code;\n"
        "}\n"
        "\n"
        f"unsigned int {name}_get_size(void)\n"
        "{\n"
        f"    return sizeof({name}_code);\n"
        "}\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description="PIOC .BIN -> C interface generator")
    ap.add_argument("--bin", required=True, help="input .BIN from WASM53B")
    ap.add_argument("--c", required=True, help="output .c path")
    ap.add_argument("--h", required=True, help="output .h path")
    ap.add_argument("--name", required=True, help="interface prefix (C identifier)")
    args = ap.parse_args()

    _check_name(args.name)
    data = _read_bin(args.bin)

    with open(args.h, "w", encoding="utf-8", newline="\n") as f:
        f.write(_gen_h(args.name))
    with open(args.c, "w", encoding="utf-8", newline="\n") as f:
        f.write(_gen_c(args.name, data, args.bin))


if __name__ == "__main__":
    main()
