set(_elf "${CMAKE_ARGV4}")
set(_size "${CMAKE_ARGV5}")
if(CMAKE_ARGC GREATER 6)
    set(_name "${CMAKE_ARGV6}")
endif()
if(CMAKE_ARGC GREATER 7)
    set(_flash_total "${CMAKE_ARGV7}")
endif()
if(CMAKE_ARGC GREATER 8)
    set(_ram_total "${CMAKE_ARGV8}")
endif()

execute_process(COMMAND "${_size}" --format=sysv "${_elf}"
    OUTPUT_VARIABLE _out RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "size failed: ${_out}")
endif()

if(DEFINED _name)
    message("")
    message("${_name} sections:")
endif()

string(REGEX MATCHALL "[A-Za-z0-9_.]+[ ]+[0-9]+[ ]+[0-9a-fA-F]+" _rows "${_out}")
foreach(_row IN LISTS _rows)
    string(REGEX REPLACE "([A-Za-z0-9_.]+)[ ]+([0-9]+)[ ]+([0-9a-fA-F]+)" "\\1;\\2;\\3" _p "${_row}")
    list(GET _p 0 _sec)
    list(GET _p 1 _sz)
    if(NOT _sz EQUAL 0)
        message("  ${_sec}: ${_sz}")
    endif()
endforeach()

message("")
if(DEFINED _flash_total AND NOT _flash_total STREQUAL "")
    message("  FLASH total: ${_flash_total}")
endif()
if(DEFINED _ram_total AND NOT _ram_total STREQUAL "")
    message("  RAM total: ${_ram_total}")
endif()
